== Classes overview

This project contains 8 classes and 0 interface.

.Classes list
[cols="<.<1d,<.<1d", %autowidth, frame=all, grid=all, stripes=none]
|===
|Classes |Interfaces

|<<Apply Theme Msg.lvclass>>
|

|<<Load Theme-Root Only Msg.lvclass>>
|

|<<Propagate Theme To Nested Appearance Actors Msg.lvclass>>
|

|<<Recieve Theme From Caller Msg.lvclass>>
|

|<<Generic Theme.lvclass>>
|

|<<ini Theme.lvclass>>
|

|<<Appearance Actor.lvclass>>
|

|<<Root Panel Actor.lvclass>>
|
|===

[plantuml, format="svg", align="center"]
....
@startuml
set namespaceSeparator :
skinparam ClassBackgroundColor #FFFFFF
skinparam ClassBorderColor #555555
skinparam ClassFontColor #000000
skinparam ClassHeaderBackgroundColor #808080

skinparam top to bottom direction
class "Appearance Actor.lvlib:Apply Theme Msg" {
{static} {method} +Send Apply Theme()
{method} +Do()

}
"Actor Framework.lvlib:Message" <|-- "Appearance Actor.lvlib:Apply Theme Msg"


class "Appearance Actor.lvlib:Load Theme-Root Only Msg" {
{field} -Theme File Path : Path
{static} {method} +Send Load Theme-Root Only()
{method} +Do()

}
"Actor Framework.lvlib:Message" <|-- "Appearance Actor.lvlib:Load Theme-Root Only Msg"


class "Appearance Actor.lvlib:Propagate Theme To Nested Appearance Actors Msg" {
{static} {method} +Send Propagate Theme To Nested Appearance Actors()
{method} +Do()

}
"Actor Framework.lvlib:Message" <|-- "Appearance Actor.lvlib:Propagate Theme To Nested Appearance Actors Msg"


class "Appearance Actor.lvlib:Recieve Theme From Caller Msg" {
{field} -Theme DVR : NoType
{static} {method} +Send Recieve Theme From Caller()
{method} +Do()

}
"Actor Framework.lvlib:Message" <|-- "Appearance Actor.lvlib:Recieve Theme From Caller Msg"


class "Appearance Actor.lvlib:Generic Theme" {
{field} +A Theme is Loaded : Boolean
{static} {method} +Default Entry Value()
{static} {method} +Style String To Bools()
{static} {method} +Theme Entry Enum To String()
{static} {method} +U32 Color To Hexa String()
{static} {method} +Hexa String To U32 Color()
{method} +Apply Light-Dark Controls Visibility()
{method} +Apply Theme To ActionButtons()
{method} +Apply Theme To CloseButton()
{method} +Apply Theme To Pane()
{method} +Apply Theme To Splitter()
{method} +Apply Theme To Title()
{method} +Load Theme()
{method} +Unload Theme()
{method} +Get Theme Info()

}


class "Appearance Actor.lvlib:ini Theme" {
{field} -ini Config Ref : NoType
{method} +Apply Light-Dark Controls Visibility()
{method} +Apply Theme To ActionButtons()
{method} +Apply Theme To CloseButton()
{method} +Apply Theme To Pane()
{method} +Apply Theme To Splitter()
{method} +Apply Theme To Title()
{method} +Load Theme()
{method} +Unload Theme()
{method} +Get Theme Info()

}
"Appearance Actor.lvlib:Generic Theme" <|-- "Appearance Actor.lvlib:ini Theme"


class "Appearance Actor.lvlib:Appearance Actor" {
{field} +Theme DVR : NoType
{field} -Panel References : Cluster
{method} +Apply Theme()
{method} +Load Theme-Root Only()
{method} +Propagate Theme To Nested Appearance Actors()
{method} +Recieve Theme From Caller()
{method} #Pre Launch Init()
{method} #Stop Core()
{method} #Substitute Actor()

}
"Panel Actor.lvlib:Panel Actor" <|-- "Appearance Actor.lvlib:Appearance Actor"


class "Root Panel.lvlib:Root Panel Actor" {
{field} -FP References : Cluster
{method} #Actor Core()

}
"Appearance Actor.lvlib:Appearance Actor" <|-- "Root Panel.lvlib:Root Panel Actor"



@enduml
....
